// <auto-generated />
using InterviewAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InterviewAssessment.Data.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("InterviewAssessment.Domain.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNull")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("AttributeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("MaxValue")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("MinValue")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowNull = false,
                            AttributeName = "FirstName",
                            AttributeType = 1,
                            MaxValue = "50",
                            MinValue = "5"
                        });
                });

            modelBuilder.Entity("InterviewAssessment.Domain.Coord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("Coords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityId = 1,
                            X = 100,
                            Y = 100
                        },
                        new
                        {
                            Id = 2,
                            EntityId = 2,
                            X = 200,
                            Y = 200
                        });
                });

            modelBuilder.Entity("InterviewAssessment.Domain.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wheels"
                        });
                });

            modelBuilder.Entity("InterviewAssessment.Domain.EntityAttributeValue", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("EntityAttributeValue");
                });

            modelBuilder.Entity("InterviewAssessment.Domain.Coord", b =>
                {
                    b.HasOne("InterviewAssessment.Domain.Entity", null)
                        .WithOne("Coordination")
                        .HasForeignKey("InterviewAssessment.Domain.Coord", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewAssessment.Domain.EntityAttributeValue", b =>
                {
                    b.HasOne("InterviewAssessment.Domain.Attribute", "Attribute")
                        .WithMany("Entities")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewAssessment.Domain.Entity", "Entity")
                        .WithMany("Attributes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
